allowBuilds:
  core-js-bundle: true
  cypress: true
  es5-ext: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - core-js-bundle
  - unrs-resolver

minimumReleaseAgeExclude:
  - jamilih@0.68.0 || 0.68.1 || 0.69.0
  - cypress@15.20.1 || 15.21.0
  - '@es-joy/jsdoccomment@0.95.0 || 0.95.1'
  - '@typescript-eslint/types@8.67.0'
  - eslint-config-ash-nazg@42.3.0 || 42.5.0 || 43.0.1
  - eslint-plugin-jsdoc@64.1.0 || 64.2.1
  - jsdoc-type-pratt-parser@9.1.1 || 9.1.2
  - zodexy@0.21.1 || 0.21.2 || 0.22.0 || 0.23.0 || 0.24.0 || 0.24.1 || 0.25.0 || 0.26.0 || 0.26.1 || 0.27.0 || 0.30.0
  - typeson-registry@13.0.1 || 13.1.0
  - typeson@10.1.1 || 10.2.0
  - '@rollup/rollup-android-arm-eabi@4.63.1'
  - '@rollup/rollup-android-arm64@4.63.1'
  - '@rollup/rollup-darwin-arm64@4.63.1'
  - '@rollup/rollup-darwin-x64@4.63.1'
  - '@rollup/rollup-freebsd-arm64@4.63.1'
  - '@rollup/rollup-freebsd-x64@4.63.1'
  - '@rollup/rollup-linux-arm-gnueabihf@4.63.1'
  - '@rollup/rollup-linux-arm-musleabihf@4.63.1'
  - '@rollup/rollup-linux-arm64-gnu@4.63.1'
  - '@rollup/rollup-linux-arm64-musl@4.63.1'
  - '@rollup/rollup-linux-loong64-gnu@4.63.1'
  - '@rollup/rollup-linux-loong64-musl@4.63.1'
  - '@rollup/rollup-linux-ppc64-gnu@4.63.1'
  - '@rollup/rollup-linux-ppc64-musl@4.63.1'
  - '@rollup/rollup-linux-riscv64-gnu@4.63.1'
  - '@rollup/rollup-linux-riscv64-musl@4.63.1'
  - '@rollup/rollup-linux-s390x-gnu@4.63.1'
  - '@rollup/rollup-linux-x64-gnu@4.63.1'
  - '@rollup/rollup-linux-x64-musl@4.63.1'
  - '@rollup/rollup-openbsd-x64@4.63.1'
  - '@rollup/rollup-openharmony-arm64@4.63.1'
  - '@rollup/rollup-win32-arm64-msvc@4.63.1'
  - '@rollup/rollup-win32-ia32-msvc@4.63.1'
  - '@rollup/rollup-win32-x64-gnu@4.63.1'
  - '@rollup/rollup-win32-x64-msvc@4.63.1'
  - eslint-plugin-escompat@3.11.6
  - rollup@4.63.1
  - zod@4.5.2

onlyBuiltDependencies:
  - cypress
