// Comment out for Cypress Cloud

import './array.cy.js';
import './arrayReference.cy.js';
import './bigint.cy.js';
import './bigintObject.cy.js';
import './blob.cy.js';
import './boolean.cy.js';
import './BooleanObject.cy.js';
import './catch.cy.js';
import './date.cy.js';
import './domexception.cy.js';
import './enum.cy.js';
import './error.cy.js';
import './file.cy.js';
import './filelist.cy.js';
import './literal.cy.js';
import './map.cy.js';
import './nan.cy.js';
import './noneditable.cy.js';
import './null.cy.js';
import './number.cy.js';
import './NumberObject.cy.js';
import './regexp.cy.js';
import './set.cy.js';
import './string.cy.js';
import './StringObject.cy.js';
import './undefined.cy.js';
import './void.cy.js';
